### ISSUE TITLE
LadyPower

### ISSUE THREAD

**Issue by carolynvs** [WriteSpeakCode/2017.writespeakcode.com#5]
Track additional activities for the conference
- [ ] organizers
- [ ] volunteers

**Comment by jarmstrng** [comment]
@carolynvs can you clarify what this is for?

**Comment by carolynvs** [comment]
This was to make it easy to for people to sign up to volunteer and also to keep track of who are organizers. Last year we needed this information for registration, t-shirts/special swag.

**Comment by jarmstrng** [comment]
@carolynvs I'm sorry I'm still confused. In what way would these additional activities be tracked? Is this for the website?

**Comment by carolynvs** [comment]
I wouldn't worry about it, if it hasn't come up it probably isn't needed.

**Comment by jarmstrng** [comment]
ok i'm going to close this then :)
